spring:
  autoconfigure:
    exclude:
    - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
    
server:
  port: 9001
  
cloud:
  aws: 
    region:
      static: us-east-1
      auto: true
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/247679585544/order-events
    queueSQS: order-events


